@startuml
class Lexer {
- String input
- int pos
- boolean isChar(char)
~ Token nextToken()
}


enum TokenType {
+  LPAREN
+  RPAREN
+  UNION
+  STAR
+  DOT
+  CHAR
+  EOF
}

class Main {
+ {static} void main(String[])
}

class Parser {
- Lexer lexer
- Token currentToken
- void eat(TokenType)
+ void parse()
- void E()
- void EPrime()
- void T()
- void TPrime()
- void F()
- void FPrime()
- void P()
- void L()
}


class Token {
~ TokenType type
~ String value
}

@enduml